site_name: NGSI-JS Library
site_description: Library NGSI
docs_dir: doc/
pages:
  - Home: index.md
  - ngsi-parser: 
    - Introduction: ngsi/index.md
    - Entities Functions: ngsi/docs/EntitiesFunctions.md
    - Generate Context Queries: ngsi/docs/ContextQueries.md
    - Data Model JSON Schema Analizer: ngsi/docs/SchemaAnalizer.md
  - ocb-sender:
    - Introduction: ocb/index.md
    - Entities Functions: ocb/docs/EntitiesFunctions.md
    - Query Functions: ocb/docs/QueryFunctions.md
    - Suscriptions Functions: ocb/docs/SubscriptionsFunctions.md
    - Implementation in the Development of Mobile Apps: ocb/docs/UsageInMobileApps.md
  - Npm Modules Usage:
    - Implementation examples of both npm modules: modulesUsage/index.md
theme: readthedocs
markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
repo_url: https://github.com/cenidetiot/ngsi-js-library
edit_uri: 'edit/master/docs/'
